hardware_acceleration: true
mode: Debug
report_background_image: configuration_creator_uploads\barilansachal.png
tests:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
users:
- email: asdasd@asdsaasdas.com
  password: sdasds
  type: Standard
