hardware_acceleration: true
mode: Production
report_background_image: configuration_creator_uploads\barilansachal.png
tests:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
users:
- email: sadas@fasdas.com
  password: asdas
  type: Standard
- email: asdsa@asdas.com
  password: asdas
  type: Admin
- email: asdasd@asdsaasdas.com
  password: asdas
  type: Admin
