hardware_acceleration: true
mode: Debug
report_background_image: configuration_creator_uploads\dd4957fa-4ca0-4ea1-86b0-2c81814aba08.jpg
tests:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
users:
- email: asdasd@asdsaasdas.com
  password: sdasds
  type: Standard
