hardware_acceleration: false
mode: Production
report_background_image: asd.png
tests:
- 1
users:
- email: admin@gmail.com
  password: admin123456
  type: Admin
- email: employee@gmail.com
  password: User123456
  type: Standard
